# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PythonDemo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install Python 3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
         python-version: 3.x
         # Optional - x64 or x86 architecture, defaults to x64
         architecture: 'x64'

      #Install dependencies   
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools

      # Install and test with pytest
      - name: Test with pytest
        run: |
         pip install pytest
         pip install pytest-cov
         pytest test.py 
